Removed base to tag tf compute; removed prints; changed Debug to Release
MRSD-Team-RoboSAR/robosar_SLAM_toolbox pull request #21
Opened 2022-10-26 22:00 UTC by jsongCMU

Tested in sim. Works fine

2022-10-26 23:50 UTC, rachelzh9 requested changes

2022-10-26 23:50 UTC, rachelzh9 commented on slam_toolbox/src/slam_toolbox_common.cpp
> +  // ROS_INFO("Apriltag %d tf calculated.", tag_id);
delete comments ?

2022-10-26 23:59 UTC, jsongCMU commented on slam_toolbox/src/slam_toolbox_common.cpp
> +  // ROS_INFO("Apriltag %d tf calculated.", tag_id);
Done

2022-10-27 00:38 UTC, rachelzh9 approved these changes
lgtm

2022-10-27 00:38 UTC, merged